<a href="https://colab.research.google.com/github/LucyKinyua/Week1_MS/blob/main/Copy_of_SQL_Programming_Selecting_%26_Retrieving_Data_with_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="green">*To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

# Selecting & Retrieving Data with SQL

## 1.1 Let's first connect to our Database

In [29]:
# We will first load the sql extension into our environment
#
%load_ext sql

# Then connect to our in memory sqlite database
# NB: This database will cease to exist as soon as the database connection is closed
#
%sql sqlite://

'Connected: @None'

## 1.2 Importing Data From a CSV File

In [30]:
# Importing the python libraries that we will need in this notebook
#
import csv
import pandas as pd

Then we will download our csv file from Interpol: [here](https://bit.ly/InterpolDataset) and World Cup [here](http://bit.ly/MSWorldCupData)  . Open the link and then on our browser  Click File > Save Page As > Save. Lastly, upload it to our current environment on Colaboratory by clicking View > Table of Contents > Files then Upload.  (NB: Do not load file from url)

In [32]:
# Loading the first table from a local CSV file
#
with open('Countries.csv','r') as f:
    Interpol = pd.read_csv(f, index_col=0, encoding='utf-8') 

# Then storing it in an SQL table of our in memory sqlite database
#
%sql PERSIST Interpol;

 * sqlite://

ValueError: ignored

In [ ]:
# We will load all the other dataset that we will need i.e. WorldCup
#
with open('WorldCup.csv','r') as f:
    WorldCup = pd.read_csv(f, index_col=0, encoding='utf-8') 
    
%sql PERSIST WorldCup;

 * sqlite://

'Persisted worldcup'

In [33]:
# Let's preview our Interpol table so that we can understand it
# Try to understand all the attributes (i.e columns) since this
# will be one of the datasets that we will work with through this session
#
%sql select * from Interpol limit 5;

 * sqlite://
Done.

[('Albania', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif'),
 ('Angola', 0, 0, 1, 'Northern Africa', 'http://www.crwflags.com/fotw/images/a/ao.gif'),
 ('Argentina', 2, 2, 1, 'South America', 'http://www.crwflags.com/fotw/images/a/ar.gif'),
 ('Australia', 1, 1, 2, 'Oceania', 'http://www.crwflags.com/fotw/images/a/au.gif'),
 ('Austria', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/at.gif')]

In [34]:
# Let's preview our Worldcup table so that we can also understand it.
# You will be acting as a football commentator performing research on the 
# world cup matches played in the past.
# 
%sql SELECT * FROM WorldCup limit 5;

 * sqlite://
Done.

[(1930, '13 Jul 1930 - 15:00 ', 'Group 1', 'Pocitos', 'Montevideo ', 'France', 4, 1, 'Mexico', ' ', 4444.0, 3, 0, 'LOMBARDI Domingo (URU)', 'CRISTOPHE Henry (BEL)', 'REGO Gilberto (BRA)', 201, 1096, 'FRA', 'MEX'),
 (1930, '13 Jul 1930 - 15:00 ', 'Group 4', 'Parque Central', 'Montevideo ', 'USA', 3, 0, 'Belgium', ' ', 18346.0, 2, 0, 'MACIAS Jose (ARG)', 'MATEUCCI Francisco (URU)', 'WARNKEN Alberto (CHI)', 201, 1090, 'USA', 'BEL'),
 (1930, '14 Jul 1930 - 12:45 ', 'Group 2', 'Parque Central', 'Montevideo ', 'Yugoslavia', 2, 1, 'Brazil', ' ', 24059.0, 2, 0, 'TEJADA Anibal (URU)', 'VALLARINO Ricardo (URU)', 'BALWAY Thomas (FRA)', 201, 1093, 'YUG', 'BRA'),
 (1930, '14 Jul 1930 - 14:50 ', 'Group 3', 'Pocitos', 'Montevideo ', 'Romania', 3, 1, 'Peru', ' ', 2549.0, 1, 0, 'WARNKEN Alberto (CHI)', 'LANGENUS Jean (BEL)', 'MATEUCCI Francisco (URU)', 201, 1098, 'ROU', 'PER'),
 (1930, '15 Jul 1930 - 16:00 ', 'Group 1', 'Parque Central', 'Montevideo ', 'Argentina', 1, 0, 'France', ' ', 23409.0, 0, 0, 'REGO Gilberto (BRA)', 'SAUCEDO Ulises (BOL)', 'RADULESCU Constantin (ROU)', 201, 1085, 'ARG', 'FRA')]

## 1.3 Select Single Columns

In [35]:
# Example 1
# This is how we will select a single column (i.e. the Country Column) from the Interpol Dataset
#
%%sql
SELECT Country FROM Interpol;

 * sqlite://
Done.

[('Albania',),
 ('Angola',),
 ('Argentina',),
 ('Australia',),
 ('Austria',),
 ('Bangladesh',),
 ('Belarus',),
 ('Belgium',),
 ('Belize',),
 ('Bolivia',),
 ('Botswana',),
 ('Brazil',),
 ('Cambodia',),
 ('Canada',),
 ('Cayman Islands',),
 ('Chile',),
 ('Colombia',),
 ('Congo',),
 ('Costa Rica',),
 ('Croatia',),
 ('Curaçao',),
 ('Czech Republic',),
 ('Denmark',),
 ('Dominican Republic',),
 ('Ecuador',),
 ('El Salvador',),
 ('Estonia',),
 ('Finland',),
 ('France',),
 ('Georgia, Asia',),
 ('Germany',),
 ('Greece',),
 ('Honduras',),
 ('Hungary',),
 ('India',),
 ('Indonesia',),
 ('Iraq',),
 ('Ireland',),
 ('Italy',),
 ('Kenya',),
 ('Lesotho',),
 ('Lithuania',),
 ('Macedonia',),
 ('Mali',),
 ('Malta',),
 ('Mexico',),
 ('Montenegro',),
 ('Morocco',),
 ('Mozambique',),
 ('Namibia',),
 ('New Zealand',),
 ('Nicaragua',),
 ('Norway',),
 ('Pakistan',),
 ('Panama',),
 ('Paraguay',),
 ('Peru',),
 ('Poland',),
 ('Qatar',),
 ('Romania',),
 ('Russia',),
 ('Serbia',),
 ('Slovakia',),
 ('Somalia',),
 ('South Africa',),
 ('Spain',),
 ('Swaziland',),
 ('Sweden',),
 ('Tanzania',),
 ('The Netherlands',),
 ('Turkey',),
 ('Ukraine',),
 ('United Kingdom',),
 ('United States',),
 ('Uruguay',),
 ('Venezuela',),
 ('Zambia',),
 ('Zimbabwe',)]

In [36]:
# Example 2
# Let's get the European countries without National fugitives  
# 
%%sql
SELECT Country FROM Interpol
WHERE 'National Fugitives' = 0 AND Region = 'Europe';

 * sqlite://
Done.

[]

In [37]:
# Example 3
# Let's select the regions without National fugitives
#
%%sql
SELECT Region FROM Interpol
WHERE 'National Fugitives' = 0

 * sqlite://
Done.

[]

### <font color="green"> 1.3 Challenges</font>

In [41]:
# Challenge 1
# Using the Interpol Dataset, let us get the Northern African countries that  
# do not host possible fugitives or captured fugitives
# 
%%sql
SELECT Country FROM Interpol
WHERE 'Possible Hosted Fugitives/Captured Fugitives' = 0 AND Region = 'Northern Africa';

 * sqlite://
Done.

[]

In [42]:
# Challenge 2
# Using the Interpol Dataset, let us get the countries without a National fugitive and a Wanted fugitive
#
%%sql
SELECT Country FROM Interpol
WHERE 'National Fugitives' = 0 AND 'Wanted Fugitive' = 0;

 * sqlite://
Done.

[]

In [43]:
# Challenge 3
# Using the Interpol Dataset, which european countries have 3 National Fugitives
# 
%%sql
SELECT Country FROM Interpol
WHERE 'National Fugitives' = 3 AND Region = 'Europe';

 * sqlite://
Done.

[]

## 1.4 Multiple columns

In [44]:
# Example 1
# Using the Interpol dataset, we would like to know the countries and their respective No. of Captured fugitives.
#
%%sql
SELECT Country, "Possible Hosted Fugitives / Captured Fugitives" FROM Interpol;

 * sqlite://
Done.

[('Albania', 0),
 ('Angola', 1),
 ('Argentina', 1),
 ('Australia', 2),
 ('Austria', 0),
 ('Bangladesh', 1),
 ('Belarus', 0),
 ('Belgium', 0),
 ('Belize', 0),
 ('Bolivia', 2),
 ('Botswana', 1),
 ('Brazil', 3),
 ('Cambodia', 1),
 ('Canada', 2),
 ('Cayman Islands', 1),
 ('Chile', 0),
 ('Colombia', 1),
 ('Congo', 1),
 ('Costa Rica', 2),
 ('Croatia', 1),
 ('Curaçao', 0),
 ('Czech Republic', 0),
 ('Denmark', 0),
 ('Dominican Republic', 2),
 ('Ecuador', 1),
 ('El Salvador', 0),
 ('Estonia', 0),
 ('Finland', 3),
 ('France', 7),
 ('Georgia, Asia', 0),
 ('Germany', 3),
 ('Greece', 3),
 ('Honduras', 1),
 ('Hungary', 0),
 ('India', 1),
 ('Indonesia', 0),
 ('Iraq', 1),
 ('Ireland', 0),
 ('Italy', 3),
 ('Kenya', 2),
 ('Lesotho', 1),
 ('Lithuania', 0),
 ('Macedonia', 1),
 ('Mali', 0),
 ('Malta', 1),
 ('Mexico', 6),
 ('Montenegro', 1),
 ('Morocco', 3),
 ('Mozambique', 2),
 ('Namibia', 1),
 ('New Zealand', 1),
 ('Nicaragua', 0),
 ('Norway', 0),
 ('Pakistan', 2),
 ('Panama', 2),
 ('Paraguay', 1),
 ('Peru', 0),
 ('Poland', 3),
 ('Qatar', 1),
 ('Romania', 0),
 ('Russia', 3),
 ('Serbia', 1),
 ('Slovakia', 0),
 ('Somalia', 0),
 ('South Africa', 4),
 ('Spain', 13),
 ('Swaziland', 1),
 ('Sweden', 1),
 ('Tanzania', 2),
 ('The Netherlands', 8),
 ('Turkey', 1),
 ('Ukraine', 1),
 ('United Kingdom', 7),
 ('United States', 6),
 ('Uruguay', 1),
 ('Venezuela', 0),
 ('Zambia', 2),
 ('Zimbabwe', 2)]

In [47]:
# Example 2
# Using the world cup dataset, let's get teams that played in the matches with their respective referee
# 
%%sql
SELECT "Home_Team_Name", "Away_Team_Name", Referee FROM WorldCup LIMIT 10;

 * sqlite://
Done.

[('France', 'Mexico', 'LOMBARDI Domingo (URU)'),
 ('USA', 'Belgium', 'MACIAS Jose (ARG)'),
 ('Yugoslavia', 'Brazil', 'TEJADA Anibal (URU)'),
 ('Romania', 'Peru', 'WARNKEN Alberto (CHI)'),
 ('Argentina', 'France', 'REGO Gilberto (BRA)'),
 ('Chile', 'Mexico', 'CRISTOPHE Henry (BEL)'),
 ('Yugoslavia', 'Bolivia', 'MATEUCCI Francisco (URU)'),
 ('USA', 'Paraguay', 'MACIAS Jose (ARG)'),
 ('Uruguay', 'Peru', 'LANGENUS Jean (BEL)'),
 ('Chile', 'France', 'TEJADA Anibal (URU)')]

In [46]:
# Example 3
# Find out any three matches that have had 5 away goals  
#
%%sql
SELECT * FROM WorldCup Where "Away_Team_Goals" = 5 LIMIT 3

 * sqlite://
Done.

[(1938, '05 Jun 1938 - 17:30 ', 'First round', 'Stade de la Meinau', 'Strasbourg ', 'Brazil', 6, 5, 'Poland', 'Brazil win after extra time ', 13452.0, 0, 0, 'EKLIND Ivan (SWE)', 'POISSANT Louis (FRA)', 'KISSENBERGER Ernest (FRA)', 206, 1150, 'BRA', 'POL'),
 (1954, '26 Jun 1954 - 17:00 ', 'Quarter-finals', 'La Pontaise', 'Lausanne ', 'Austria', 7, 5, 'Switzerland', ' ', 35000.0, 5, 4, 'FAULTLESS Charlie (SCO)', 'ASENSI Manuel (ESP)', 'SCHMETZER Emil (FRG)', 212, 1237, 'AUT', 'SUI'),
 (1986, '18 Jun 1986 - 16:00 ', 'Round of 16', 'Estadio Corregidora', 'Queretaro ', 'Denmark', 1, 5, 'Spain', ' ', 38500.0, 1, 1, 'KEIZER Jan (NED)', 'BENNACEUR Ali (TUN)', 'DOTCHEV Bogdan (BUL)', 309, 511, 'DEN', 'ESP')]

### <font color="green"> 1.4 Challenges</font>

In [50]:
# Challenge 1
# From the Interpol dataset, let's get countries with their respective 
# No. of National fugitives and Wanted fugitives
# 
%%sql
SELECT * FROM Interpol WHERE "National Fugitives" AND "Wanted Fugitives" LIMIT 5

 * sqlite://
Done.

[('Albania', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif'),
 ('Argentina', 2, 2, 1, 'South America', 'http://www.crwflags.com/fotw/images/a/ar.gif'),
 ('Australia', 1, 1, 2, 'Oceania', 'http://www.crwflags.com/fotw/images/a/au.gif'),
 ('Austria', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/at.gif'),
 ('Bangladesh', 2, 1, 1, 'Asia', 'http://www.crwflags.com/fotw/images/b/bd.gif')]

In [59]:
# Challenge 2
# Using WorldCup dataset, find out which group 4 world cup matches 
# that were played in the city of Montevideo 
#
%%sql
SELECT * FROM WorldCup WHERE Stage = "Group 4" AND City = "Montevideo";

 * sqlite://
Done.

[]

In [60]:
# Challenge 3
# Answering the same question as challenge 2, we would like to get only one match
# 
# WorldCup.head(2)
%%sql
SELECT * FROM WorldCup Where Stage = "Group 1" AND City = "Montevideo"

 * sqlite://
Done.

[]

In [ ]:
WorldCup["City"].value_counts()

Mexico City        23
Rio De Janeiro     18
Montevideo         18
Guadalajara        17
Johannesburg       15
                   ..
Strasbourg          1
Udevalla            1
Reims               1
Antibes             1
Lille               1
Name: City, Length: 151, dtype: int64

In [ ]:
%%sql
SELECT * FROM WorldCup 
WHERE City="Montevideo " AND Stage="Group 1";

 * sqlite://
Done.

[(1930, '13 Jul 1930 - 15:00 ', 'Group 1', 'Pocitos', 'Montevideo ', 'France', 4, 1, 'Mexico', ' ', 4444.0, 3, 0, 'LOMBARDI Domingo (URU)', 'CRISTOPHE Henry (BEL)', 'REGO Gilberto (BRA)', 201, 1096, 'FRA', 'MEX'),
 (1930, '15 Jul 1930 - 16:00 ', 'Group 1', 'Parque Central', 'Montevideo ', 'Argentina', 1, 0, 'France', ' ', 23409.0, 0, 0, 'REGO Gilberto (BRA)', 'SAUCEDO Ulises (BOL)', 'RADULESCU Constantin (ROU)', 201, 1085, 'ARG', 'FRA'),
 (1930, '16 Jul 1930 - 14:45 ', 'Group 1', 'Parque Central', 'Montevideo ', 'Chile', 3, 0, 'Mexico', ' ', 9249.0, 1, 0, 'CRISTOPHE Henry (BEL)', 'APHESTEGUY Martin (URU)', 'LANGENUS Jean (BEL)', 201, 1095, 'CHI', 'MEX'),
 (1930, '19 Jul 1930 - 12:50 ', 'Group 1', 'Estadio Centenario', 'Montevideo ', 'Chile', 1, 0, 'France', ' ', 2000.0, 0, 0, 'TEJADA Anibal (URU)', 'LOMBARDI Domingo (URU)', 'REGO Gilberto (BRA)', 201, 1094, 'CHI', 'FRA'),
 (1930, '19 Jul 1930 - 15:00 ', 'Group 1', 'Estadio Centenario', 'Montevideo ', 'Argentina', 6, 3, 'Mexico', ' ', 42100.0, 3, 1, 'SAUCEDO Ulises (BOL)', 'ALONSO Gualberto (URU)', 'RADULESCU Constantin (ROU)', 201, 1086, 'ARG', 'MEX'),
 (1930, '22 Jul 1930 - 14:45 ', 'Group 1', 'Estadio Centenario', 'Montevideo ', 'Argentina', 3, 1, 'Chile', ' ', 41459.0, 2, 1, 'LANGENUS Jean (BEL)', 'CRISTOPHE Henry (BEL)', 'SAUCEDO Ulises (BOL)', 201, 1084, 'ARG', 'CHI')]

In [ ]:
%%sql
SELECT * FROM Interpol LIMIT 10;

 * sqlite://
Done.

[('Albania', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif'),
 ('Angola', 0, 0, 1, 'Northern Africa', 'http://www.crwflags.com/fotw/images/a/ao.gif'),
 ('Argentina', 2, 2, 1, 'South America', 'http://www.crwflags.com/fotw/images/a/ar.gif'),
 ('Australia', 1, 1, 2, 'Oceania', 'http://www.crwflags.com/fotw/images/a/au.gif'),
 ('Austria', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/at.gif'),
 ('Bangladesh', 2, 1, 1, 'Asia', 'http://www.crwflags.com/fotw/images/b/bd.gif'),
 ('Belarus', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/by.gif'),
 ('Belgium', 0, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/be.gif'),
 ('Belize', 1, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/b/bz.gif'),
 ('Bolivia', 0, 0, 2, 'South America', 'http://www.crwflags.com/fotw/images/b/bo.gif')]

In [ ]:
# SELECT Country FROM Interpol LIMIT 10;
Interpol.columns.values

array(['National Fugitives', 'Wanted Fugitives',
       'Possible Hosted Fugitives / Captured Fugitives', 'Region', 'Flag'],
      dtype=object)

## 1.5 Orderby

In [51]:
# Example 1
# Using the Interpol dataset, let's get all our records ordering 
# them by the region in ascending order
#
%%sql
SELECT * FROM Interpol
ORDER BY Region ASC;

 * sqlite://
Done.

[('Bangladesh', 2, 1, 1, 'Asia', 'http://www.crwflags.com/fotw/images/b/bd.gif'),
 ('Cambodia', 0, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/k/kh.gif'),
 ('Georgia, Asia', 2, 2, 0, 'Asia', 'http://www.crwflags.com/fotw/images/g/ge.gif'),
 ('India', 0, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/i/in.gif'),
 ('Indonesia', 1, 1, 0, 'Asia', 'http://www.crwflags.com/fotw/images/i/id.gif'),
 ('Iraq', 1, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/i/iq.gif'),
 ('Pakistan', 1, 0, 2, 'Asia', 'http://www.crwflags.com/fotw/images/p/pk.gif'),
 ('Qatar', 0, 0, 1, 'Asia', 'http://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg'),
 ('Belize', 1, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/b/bz.gif'),
 ('Cayman Islands', 0, 0, 1, 'Central America', 'http://www.crwflags.com/fotw/images/k/ky.gif'),
 ('Costa Rica', 0, 1, 2, 'Central America', 'http://www.crwflags.com/fotw/images/c/cr.gif'),
 ('Curaçao', 0, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/c/cw.gif'),
 ('Dominican Republic', 1, 1, 2, 'Central America', 'http://www.crwflags.com/fotw/images/d/do.gif'),
 ('El Salvador', 2, 2, 0, 'Central America', 'http://www.crwflags.com/fotw/images/s/sv.gif'),
 ('Honduras', 1, 0, 1, 'Central America', 'http://www.crwflags.com/fotw/images/h/hn.gif'),
 ('Mexico', 3, 0, 6, 'Central America', 'http://www.crwflags.com/fotw/images/m/mx.gif'),
 ('Nicaragua', 1, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/n/ni.gif'),
 ('Panama', 0, 0, 2, 'Central America', 'http://www.crwflags.com/fotw/images/p/pa.gif'),
 ('Albania', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif'),
 ('Austria', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/at.gif'),
 ('Belarus', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/by.gif'),
 ('Belgium', 0, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/be.gif'),
 ('Croatia', 1, 1, 1, 'Europe', 'http://www.crwflags.com/fotw/images/h/hr.gif'),
 ('Czech Republic', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/c/cz.gif'),
 ('Denmark', 0, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/d/dk.gif'),
 ('Estonia', 1, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/e/ee.gif'),
 ('Finland', 2, 2, 3, 'Europe', 'http://www.crwflags.com/fotw/images/f/fi.gif'),
 ('France', 0, 0, 7, 'Europe', 'http://www.crwflags.com/fotw/images/f/fr.gif'),
 ('Germany', 1, 0, 3, 'Europe', 'http://www.crwflags.com/fotw/images/d/de.gif'),
 ('Greece', 1, 1, 3, 'Europe', 'http://www.crwflags.com/fotw/images/g/gr.gif'),
 ('Hungary', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/h/hu.gif'),
 ('Ireland', 2, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/i/ie.gif'),
 ('Italy', 1, 1, 3, 'Europe', 'http://www.crwflags.com/fotw/images/i/it.gif'),
 ('Lithuania', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/l/lt.gif'),
 ('Macedonia', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/mk.gif'),
 ('Malta', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/mt.gif'),
 ('Montenegro', 3, 2, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/me.gif'),
 ('Norway', 0, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/n/no.gif'),
 ('Poland', 4, 4, 3, 'Europe', 'http://www.crwflags.com/fotw/images/p/pl.gif'),
 ('Romania', 4, 4, 0, 'Europe', 'http://www.crwflags.com/fotw/images/r/ro.gif'),
 ('Serbia', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/r/rs.gif'),
 ('Slovakia', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/s/sk.gif'),
 ('Spain', 1, 2, 13, 'Europe', 'http://www.crwflags.com/fotw/images/e/es.gif'),
 ('Sweden', 2, 3, 1, 'Europe', 'http://www.crwflags.com/fotw/images/s/se.gif'),
 ('The Netherlands', 6, 3, 8, 'Europe', 'http://www.crwflags.com/fotw/images/n/nl.gif'),
 ('Turkey', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/t/tr.gif'),
 ('Ukraine', 1, 1, 1, 'Europe', 'http://www.crwflags.com/fotw/images/u/ua.gif'),
 ('United Kingdom', 6, 4, 7, 'Europe', 'http://www.crwflags.com/fotw/images/g/gb.gif'),
 ('Russia', 2, 1, 3, 'Europe, Asia', 'http://www.crwflags.com/fotw/images/r/ru.gif'),
 ('Canada', 3, 4, 2, 'North America', 'http://www.crwflags.com/fotw/images/c/ca.gif'),
 ('United States', 8, 11, 6, 'North America', 'http://www.crwflags.com/fotw/images/u/us.gif'),
 ('Angola', 0, 0, 1, 'Northern Africa', 'http://www.crwflags.com/fotw/images/a/ao.gif'),
 ('Morocco', 2, 0, 3, 'Northern Africa', 'http://www.crwflags.com/fotw/images/m/ma.gif'),
 ('Australia', 1, 1, 2, 'Oceania', 'http://www.crwflags.com/fotw/images/a/au.gif'),
 ('New Zealand', 0, 0, 1, 'Oceania', 'http://www.crwflags.com/fotw/images/n/nz.gif'),
 ('Argentina', 2, 2, 1, 'South America', 'http://www.crwflags.com/fotw/images/a/ar.gif'),
 ('Bolivia', 0, 0, 2, 'South America', 'http://www.crwflags.com/fotw/images/b/bo.gif'),
 ('Brazil', 2, 4, 3, 'South America', 'http://www.crwflags.com/fotw/images/b/br.gif'),
 ('Chile', 1, 1, 0, 'South America', 'http://www.crwflags.com/fotw/images/c/cl.gif'),
 ('Colombia', 3, 0, 1, 'South America', 'http://www.crwflags.com/fotw/images/c/co.gif'),
 ('Ecuador', 0, 0, 1, 'South America', 'http://www.worldatlas.com/webimage/flags/countrys/zzzflags/eclarge.jpg'),
 ('Paraguay', 1, 1, 1, 'South America', 'http://www.crwflags.com/fotw/images/p/py.gif'),
 ('Peru', 2, 1, 0, 'South America', 'http://www.crwflags.com/fotw/images/p/pe.gif'),
 ('Uruguay', 1, 1, 1, 'South America', 'http://www.crwflags.com/fotw/images/u/uy.gif'),
 ('Venezuela', 0, 1, 0, 'South America', 'http://www.crwflags.com/fotw/images/v/ve.gif'),
 ('Botswana', 0, 1, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/b/bw.gif'),
 ('Lesotho', 0, 0, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/l/ls.gif'),
 ('Mozambique', 0, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/m/mz.gif'),
 ('Namibia', 0, 0, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/n/na.gif'),
 ('South Africa', 3, 2, 4, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/za.gif'),
 ('Swaziland', 1, 1, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/s/sz.gif'),
 ('Zambia', 1, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/zm.gif'),
 ('Zimbabwe', 0, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/zw.gif'),
 ('Congo', 0, 0, 1, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/c/cg.gif'),
 ('Kenya', 1, 1, 2, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/k/ke.gif'),
 ('Mali', 0, 1, 0, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/m/ml.gif'),
 ('Somalia', 1, 0, 0, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/s/so.gif'),
 ('Tanzania', 0, 1, 2, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/t/tz.gif')]

In [61]:
# Example 2
# We can do the same as in example 1 but now having the records in descending order 
# as shown below
#
%%sql
SELECT * FROM Interpol
ORDER BY Country DESC;

 * sqlite://
Done.

[('Zimbabwe', 0, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/zw.gif'),
 ('Zambia', 1, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/zm.gif'),
 ('Venezuela', 0, 1, 0, 'South America', 'http://www.crwflags.com/fotw/images/v/ve.gif'),
 ('Uruguay', 1, 1, 1, 'South America', 'http://www.crwflags.com/fotw/images/u/uy.gif'),
 ('United States', 8, 11, 6, 'North America', 'http://www.crwflags.com/fotw/images/u/us.gif'),
 ('United Kingdom', 6, 4, 7, 'Europe', 'http://www.crwflags.com/fotw/images/g/gb.gif'),
 ('Ukraine', 1, 1, 1, 'Europe', 'http://www.crwflags.com/fotw/images/u/ua.gif'),
 ('Turkey', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/t/tr.gif'),
 ('The Netherlands', 6, 3, 8, 'Europe', 'http://www.crwflags.com/fotw/images/n/nl.gif'),
 ('Tanzania', 0, 1, 2, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/t/tz.gif'),
 ('Sweden', 2, 3, 1, 'Europe', 'http://www.crwflags.com/fotw/images/s/se.gif'),
 ('Swaziland', 1, 1, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/s/sz.gif'),
 ('Spain', 1, 2, 13, 'Europe', 'http://www.crwflags.com/fotw/images/e/es.gif'),
 ('South Africa', 3, 2, 4, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/za.gif'),
 ('Somalia', 1, 0, 0, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/s/so.gif'),
 ('Slovakia', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/s/sk.gif'),
 ('Serbia', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/r/rs.gif'),
 ('Russia', 2, 1, 3, 'Europe, Asia', 'http://www.crwflags.com/fotw/images/r/ru.gif'),
 ('Romania', 4, 4, 0, 'Europe', 'http://www.crwflags.com/fotw/images/r/ro.gif'),
 ('Qatar', 0, 0, 1, 'Asia', 'http://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg'),
 ('Poland', 4, 4, 3, 'Europe', 'http://www.crwflags.com/fotw/images/p/pl.gif'),
 ('Peru', 2, 1, 0, 'South America', 'http://www.crwflags.com/fotw/images/p/pe.gif'),
 ('Paraguay', 1, 1, 1, 'South America', 'http://www.crwflags.com/fotw/images/p/py.gif'),
 ('Panama', 0, 0, 2, 'Central America', 'http://www.crwflags.com/fotw/images/p/pa.gif'),
 ('Pakistan', 1, 0, 2, 'Asia', 'http://www.crwflags.com/fotw/images/p/pk.gif'),
 ('Norway', 0, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/n/no.gif'),
 ('Nicaragua', 1, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/n/ni.gif'),
 ('New Zealand', 0, 0, 1, 'Oceania', 'http://www.crwflags.com/fotw/images/n/nz.gif'),
 ('Namibia', 0, 0, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/n/na.gif'),
 ('Mozambique', 0, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/m/mz.gif'),
 ('Morocco', 2, 0, 3, 'Northern Africa', 'http://www.crwflags.com/fotw/images/m/ma.gif'),
 ('Montenegro', 3, 2, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/me.gif'),
 ('Mexico', 3, 0, 6, 'Central America', 'http://www.crwflags.com/fotw/images/m/mx.gif'),
 ('Malta', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/mt.gif'),
 ('Mali', 0, 1, 0, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/m/ml.gif'),
 ('Macedonia', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/mk.gif'),
 ('Lithuania', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/l/lt.gif'),
 ('Lesotho', 0, 0, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/l/ls.gif'),
 ('Kenya', 1, 1, 2, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/k/ke.gif'),
 ('Italy', 1, 1, 3, 'Europe', 'http://www.crwflags.com/fotw/images/i/it.gif'),
 ('Ireland', 2, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/i/ie.gif'),
 ('Iraq', 1, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/i/iq.gif'),
 ('Indonesia', 1, 1, 0, 'Asia', 'http://www.crwflags.com/fotw/images/i/id.gif'),
 ('India', 0, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/i/in.gif'),
 ('Hungary', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/h/hu.gif'),
 ('Honduras', 1, 0, 1, 'Central America', 'http://www.crwflags.com/fotw/images/h/hn.gif'),
 ('Greece', 1, 1, 3, 'Europe', 'http://www.crwflags.com/fotw/images/g/gr.gif'),
 ('Germany', 1, 0, 3, 'Europe', 'http://www.crwflags.com/fotw/images/d/de.gif'),
 ('Georgia, Asia', 2, 2, 0, 'Asia', 'http://www.crwflags.com/fotw/images/g/ge.gif'),
 ('France', 0, 0, 7, 'Europe', 'http://www.crwflags.com/fotw/images/f/fr.gif'),
 ('Finland', 2, 2, 3, 'Europe', 'http://www.crwflags.com/fotw/images/f/fi.gif'),
 ('Estonia', 1, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/e/ee.gif'),
 ('El Salvador', 2, 2, 0, 'Central America', 'http://www.crwflags.com/fotw/images/s/sv.gif'),
 ('Ecuador', 0, 0, 1, 'South America', 'http://www.worldatlas.com/webimage/flags/countrys/zzzflags/eclarge.jpg'),
 ('Dominican Republic', 1, 1, 2, 'Central America', 'http://www.crwflags.com/fotw/images/d/do.gif'),
 ('Denmark', 0, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/d/dk.gif'),
 ('Czech Republic', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/c/cz.gif'),
 ('Curaçao', 0, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/c/cw.gif'),
 ('Croatia', 1, 1, 1, 'Europe', 'http://www.crwflags.com/fotw/images/h/hr.gif'),
 ('Costa Rica', 0, 1, 2, 'Central America', 'http://www.crwflags.com/fotw/images/c/cr.gif'),
 ('Congo', 0, 0, 1, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/c/cg.gif'),
 ('Colombia', 3, 0, 1, 'South America', 'http://www.crwflags.com/fotw/images/c/co.gif'),
 ('Chile', 1, 1, 0, 'South America', 'http://www.crwflags.com/fotw/images/c/cl.gif'),
 ('Cayman Islands', 0, 0, 1, 'Central America', 'http://www.crwflags.com/fotw/images/k/ky.gif'),
 ('Canada', 3, 4, 2, 'North America', 'http://www.crwflags.com/fotw/images/c/ca.gif'),
 ('Cambodia', 0, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/k/kh.gif'),
 ('Brazil', 2, 4, 3, 'South America', 'http://www.crwflags.com/fotw/images/b/br.gif'),
 ('Botswana', 0, 1, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/b/bw.gif'),
 ('Bolivia', 0, 0, 2, 'South America', 'http://www.crwflags.com/fotw/images/b/bo.gif'),
 ('Belize', 1, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/b/bz.gif'),
 ('Belgium', 0, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/be.gif'),
 ('Belarus', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/by.gif'),
 ('Bangladesh', 2, 1, 1, 'Asia', 'http://www.crwflags.com/fotw/images/b/bd.gif'),
 ('Austria', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/at.gif'),
 ('Australia', 1, 1, 2, 'Oceania', 'http://www.crwflags.com/fotw/images/a/au.gif'),
 ('Argentina', 2, 2, 1, 'South America', 'http://www.crwflags.com/fotw/images/a/ar.gif'),
 ('Angola', 0, 0, 1, 'Northern Africa', 'http://www.crwflags.com/fotw/images/a/ao.gif'),
 ('Albania', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif')]

In [62]:
# Example 3 
# Using the Worldcup dataset, we can select 5 World Cup Group 1 matches played 
# after 1950 and having them ordered by city in ascending order as shown below
#
%%sql
SELECT * FROM WorldCup
WHERE Stage='Group 1' AND Year > 1950
ORDER BY City ASC
LIMIT 5;

 * sqlite://
Done.

[(1962, '30 May 1962 - 15:00 ', 'Group 1', 'Carlos Dittborn', 'Arica ', 'Uruguay', 2, 1, 'Colombia', ' ', 7908.0, 0, 1, 'DOROGI Andor (HUN)', 'ETZEL FILHO Joao (BRA)', 'GALBA Karol (TCH)', 231, 1479, 'URU', 'COL'),
 (1962, '31 May 1962 - 15:00 ', 'Group 1', 'Carlos Dittborn', 'Arica ', 'Soviet Union', 2, 0, 'Yugoslavia', ' ', 9622.0, 0, 0, 'DUSCH Albert (GER)', 'ETZEL FILHO Joao (BRA)', 'ROBLES Carlos (CHI)', 231, 1563, 'URS', 'YUG'),
 (1962, '02 Jun 1962 - 15:00 ', 'Group 1', 'Carlos Dittborn', 'Arica ', 'Yugoslavia', 3, 1, 'Uruguay', ' ', 8829.0, 2, 1, 'GALBA Karol (TCH)', 'DUSCH Albert (GER)', 'JONNI Cesare (ITA)', 231, 1564, 'YUG', 'URU'),
 (1962, '03 Jun 1962 - 15:00 ', 'Group 1', 'Carlos Dittborn', 'Arica ', 'Soviet Union', 4, 4, 'Colombia', ' ', 8040.0, 3, 1, 'ETZEL FILHO Joao (BRA)', 'DOROGI Andor (HUN)', 'ROBLES Carlos (CHI)', 231, 1478, 'URS', 'COL'),
 (1962, '06 Jun 1962 - 15:00 ', 'Group 1', 'Carlos Dittborn', 'Arica ', 'Soviet Union', 2, 1, 'Uruguay', ' ', 9973.0, 1, 0, 'JONNI Cesare (ITA)', 'DOROGI Andor (HUN)', 'DUSCH Albert (GER)', 231, 1562, 'URS', 'URU')]

### <font color="green"> 1.5 Challenges</font>

In [64]:
# Challenge 1
# Using Interpol Dataset, select all the records and order them by National Fugitives in ascending order
# 
%%sql
SELECT * FROM Interpol
ORDER BY "National Fugitives" ASC;

 * sqlite://
Done.

[('Angola', 0, 0, 1, 'Northern Africa', 'http://www.crwflags.com/fotw/images/a/ao.gif'),
 ('Belgium', 0, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/be.gif'),
 ('Bolivia', 0, 0, 2, 'South America', 'http://www.crwflags.com/fotw/images/b/bo.gif'),
 ('Botswana', 0, 1, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/b/bw.gif'),
 ('Cambodia', 0, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/k/kh.gif'),
 ('Cayman Islands', 0, 0, 1, 'Central America', 'http://www.crwflags.com/fotw/images/k/ky.gif'),
 ('Congo', 0, 0, 1, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/c/cg.gif'),
 ('Costa Rica', 0, 1, 2, 'Central America', 'http://www.crwflags.com/fotw/images/c/cr.gif'),
 ('Curaçao', 0, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/c/cw.gif'),
 ('Denmark', 0, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/d/dk.gif'),
 ('Ecuador', 0, 0, 1, 'South America', 'http://www.worldatlas.com/webimage/flags/countrys/zzzflags/eclarge.jpg'),
 ('France', 0, 0, 7, 'Europe', 'http://www.crwflags.com/fotw/images/f/fr.gif'),
 ('India', 0, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/i/in.gif'),
 ('Lesotho', 0, 0, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/l/ls.gif'),
 ('Macedonia', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/mk.gif'),
 ('Mali', 0, 1, 0, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/m/ml.gif'),
 ('Malta', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/mt.gif'),
 ('Mozambique', 0, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/m/mz.gif'),
 ('Namibia', 0, 0, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/n/na.gif'),
 ('New Zealand', 0, 0, 1, 'Oceania', 'http://www.crwflags.com/fotw/images/n/nz.gif'),
 ('Norway', 0, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/n/no.gif'),
 ('Panama', 0, 0, 2, 'Central America', 'http://www.crwflags.com/fotw/images/p/pa.gif'),
 ('Qatar', 0, 0, 1, 'Asia', 'http://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg'),
 ('Serbia', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/r/rs.gif'),
 ('Tanzania', 0, 1, 2, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/t/tz.gif'),
 ('Turkey', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/t/tr.gif'),
 ('Venezuela', 0, 1, 0, 'South America', 'http://www.crwflags.com/fotw/images/v/ve.gif'),
 ('Zimbabwe', 0, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/zw.gif'),
 ('Australia', 1, 1, 2, 'Oceania', 'http://www.crwflags.com/fotw/images/a/au.gif'),
 ('Austria', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/at.gif'),
 ('Belarus', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/by.gif'),
 ('Belize', 1, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/b/bz.gif'),
 ('Chile', 1, 1, 0, 'South America', 'http://www.crwflags.com/fotw/images/c/cl.gif'),
 ('Croatia', 1, 1, 1, 'Europe', 'http://www.crwflags.com/fotw/images/h/hr.gif'),
 ('Dominican Republic', 1, 1, 2, 'Central America', 'http://www.crwflags.com/fotw/images/d/do.gif'),
 ('Estonia', 1, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/e/ee.gif'),
 ('Germany', 1, 0, 3, 'Europe', 'http://www.crwflags.com/fotw/images/d/de.gif'),
 ('Greece', 1, 1, 3, 'Europe', 'http://www.crwflags.com/fotw/images/g/gr.gif'),
 ('Honduras', 1, 0, 1, 'Central America', 'http://www.crwflags.com/fotw/images/h/hn.gif'),
 ('Indonesia', 1, 1, 0, 'Asia', 'http://www.crwflags.com/fotw/images/i/id.gif'),
 ('Iraq', 1, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/i/iq.gif'),
 ('Italy', 1, 1, 3, 'Europe', 'http://www.crwflags.com/fotw/images/i/it.gif'),
 ('Kenya', 1, 1, 2, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/k/ke.gif'),
 ('Lithuania', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/l/lt.gif'),
 ('Nicaragua', 1, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/n/ni.gif'),
 ('Pakistan', 1, 0, 2, 'Asia', 'http://www.crwflags.com/fotw/images/p/pk.gif'),
 ('Paraguay', 1, 1, 1, 'South America', 'http://www.crwflags.com/fotw/images/p/py.gif'),
 ('Somalia', 1, 0, 0, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/s/so.gif'),
 ('Spain', 1, 2, 13, 'Europe', 'http://www.crwflags.com/fotw/images/e/es.gif'),
 ('Swaziland', 1, 1, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/s/sz.gif'),
 ('Ukraine', 1, 1, 1, 'Europe', 'http://www.crwflags.com/fotw/images/u/ua.gif'),
 ('Uruguay', 1, 1, 1, 'South America', 'http://www.crwflags.com/fotw/images/u/uy.gif'),
 ('Zambia', 1, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/zm.gif'),
 ('Argentina', 2, 2, 1, 'South America', 'http://www.crwflags.com/fotw/images/a/ar.gif'),
 ('Bangladesh', 2, 1, 1, 'Asia', 'http://www.crwflags.com/fotw/images/b/bd.gif'),
 ('Brazil', 2, 4, 3, 'South America', 'http://www.crwflags.com/fotw/images/b/br.gif'),
 ('El Salvador', 2, 2, 0, 'Central America', 'http://www.crwflags.com/fotw/images/s/sv.gif'),
 ('Finland', 2, 2, 3, 'Europe', 'http://www.crwflags.com/fotw/images/f/fi.gif'),
 ('Georgia, Asia', 2, 2, 0, 'Asia', 'http://www.crwflags.com/fotw/images/g/ge.gif'),
 ('Hungary', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/h/hu.gif'),
 ('Ireland', 2, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/i/ie.gif'),
 ('Morocco', 2, 0, 3, 'Northern Africa', 'http://www.crwflags.com/fotw/images/m/ma.gif'),
 ('Peru', 2, 1, 0, 'South America', 'http://www.crwflags.com/fotw/images/p/pe.gif'),
 ('Russia', 2, 1, 3, 'Europe, Asia', 'http://www.crwflags.com/fotw/images/r/ru.gif'),
 ('Slovakia', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/s/sk.gif'),
 ('Sweden', 2, 3, 1, 'Europe', 'http://www.crwflags.com/fotw/images/s/se.gif'),
 ('Albania', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif'),
 ('Canada', 3, 4, 2, 'North America', 'http://www.crwflags.com/fotw/images/c/ca.gif'),
 ('Colombia', 3, 0, 1, 'South America', 'http://www.crwflags.com/fotw/images/c/co.gif'),
 ('Czech Republic', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/c/cz.gif'),
 ('Mexico', 3, 0, 6, 'Central America', 'http://www.crwflags.com/fotw/images/m/mx.gif'),
 ('Montenegro', 3, 2, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/me.gif'),
 ('South Africa', 3, 2, 4, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/za.gif'),
 ('Poland', 4, 4, 3, 'Europe', 'http://www.crwflags.com/fotw/images/p/pl.gif'),
 ('Romania', 4, 4, 0, 'Europe', 'http://www.crwflags.com/fotw/images/r/ro.gif'),
 ('The Netherlands', 6, 3, 8, 'Europe', 'http://www.crwflags.com/fotw/images/n/nl.gif'),
 ('United Kingdom', 6, 4, 7, 'Europe', 'http://www.crwflags.com/fotw/images/g/gb.gif'),
 ('United States', 8, 11, 6, 'North America', 'http://www.crwflags.com/fotw/images/u/us.gif')]

In [68]:
# Challenge 2
# Using WorldCup Dataset, get the matches played in the Pocitos stadium and their attendance 
# later than 1950 and ordering them by attendance in descending order
# 
%%sql
SELECT * FROM WorldCup
WHERE Stadium = 'Pocitos' AND Year > 1950
ORDER BY Attendance ASC;

 * sqlite://
Done.

[]

In [65]:
# Challenge 3
# Get the World Cup Matches played in France after 1970 ordered by years in descending order 
#
%%sql
SELECT * FROM WorldCup
WHERE Home_Team_Name = 'France' AND Year > 1970
ORDER BY Year ASC;

 * sqlite://
Done.

[(1978, '10 Jun 1978 - 15:10 ', 'Group 1', 'Estadio Jos� Mar�a Minella', 'Mar Del Plata ', 'France', 3, 1, 'Hungary', ' ', 23127.0, 3, 1, 'COELHO Arnaldo (BRA)', 'PARTRIDGE Pat (ENG)', 'SILVAGNO CAVANNA Juan (CHI)', 278, 2344, 'FRA', 'HUN'),
 (1982, '21 Jun 1982 - 17:15 ', 'Group 4', 'Jose Zorrilla', 'Valladolid ', 'France', 4, 1, 'Kuwait', ' ', 30043.0, 2, 0, 'STUPAR Miroslav (URS)', 'FREDRIKSSON Erik (SWE)', 'MATOVINOVIC Damir (CRO)', 293, 919, 'FRA', 'KUW'),
 (1982, '24 Jun 1982 - 17:15 ', 'Group 4', 'Jose Zorrilla', 'Valladolid ', 'France', 1, 1, 'Czechoslovakia', ' ', 28000.0, 0, 0, 'CASARIN Paolo (ITA)', 'DWOMOH Benjamin (GHA)', 'PALOTAI Karoly (HUN)', 293, 922, 'FRA', 'TCH'),
 (1982, '04 Jul 1982 - 17:15 ', 'Group 4', 'Vicente Calderon', 'Madrid ', 'France', 4, 1, 'Northern Ireland', ' ', 37000.0, 1, 0, 'JARGUZ Alojzy (POL)', 'RAINEA Nicolae (ROU)', 'EL GHOUL Yusef Mohamed (LBY)', 294, 920, 'FRA', 'NIR'),
 (1986, '05 Jun 1986 - 12:00 ', 'Group C', 'Nou Camp - Estadio Le�n', 'Leon ', 'France', 1, 1, 'Soviet Union', ' ', 36540.0, 0, 0, 'ARPPI FILHO Romualdo (BRA)', 'SANCHEZ ARMINIO Victoriano (ESP)', 'TAKADA Shizuo (JPN)', 308, 571, 'FRA', 'URS'),
 (1986, '25 Jun 1986 - 12:00 ', 'Semi-finals', 'Jalisco', 'Guadalajara ', 'France', 0, 2, 'Germany FR', ' ', 45000.0, 0, 1, 'AGNOLIN Luigi (ITA)', 'PETROVIC Zoran (SRB)', 'NEMETH Lajos (HUN)', 3469, 564, 'FRA', 'FRG'),
 (1986, '28 Jun 1986 - 12:00 ', 'Match for third place', 'Cuauhtemoc', 'Puebla ', 'France', 4, 2, 'Belgium', 'France win after extra time ', 21000.0, 0, 0, 'COURTNEY George (ENG)', 'SILVA ARCE Hernan (CHI)', 'AL SHARIF Jamal (SYR)', 3468, 422, 'FRA', 'BEL'),
 (1998, '12 Jun 1998 - 21:00 ', 'Group C', 'Stade V�lodrome', 'Marseilles ', 'France', 3, 0, 'South Africa', ' ', 55000.0, 1, 0, 'REZENDE Marcio (BRA)', 'PINTO Arnaldo (BRA)', 'GONZALES Merere (TRI)', 1014, 8730, 'FRA', 'RSA'),
 (1998, '18 Jun 1998 - 21:00 ', 'Group C', 'Stade de France', 'Saint-Denis ', 'France', 4, 0, 'Saudi Arabia', ' ', 80000.0, 1, 0, 'BRIZIO CARTER Arturo (MEX)', 'SALINAS Reynaldo (HON)', 'TORRES ZUNIGA Luis (CRC)', 1014, 8745, 'FRA', 'KSA'),
 (1998, '24 Jun 1998 - 16:00 ', 'Group C', 'Stade de Gerland', 'Lyon ', 'France', 2, 1, 'Denmark', ' ', 39100.0, 1, 1, 'COLLINA Pierluigi (ITA)', 'VAN DEN BROECK Marc (BEL)', 'ZAMMIT Emanuel (MLT)', 1014, 8762, 'FRA', 'DEN'),
 (1998, '28 Jun 1998 - 16:30 ', 'Round of 16', 'Stade Felix Bollaert', 'Lens ', 'France', 1, 0, 'Paraguay', 'France win after extra time ', 31800.0, 0, 0, 'BUJSAIM Ali (UAE)', 'WICKRAMATUNGA Nimal (SRI)', 'FRED Lencie (VAN)', 1024, 8776, 'FRA', 'PAR'),
 (1998, '08 Jul 1998 - 21:00 ', 'Semi-finals', 'Stade de France', 'Saint-Denis ', 'France', 2, 1, 'Croatia', ' ', 76000.0, 0, 0, 'GARCIA ARANDA Jose Maria (ESP)', 'TRESACO GRACIA Fernando (ESP)', 'DIAZ GALVEZ Jorge (CHI)', 1026, 8786, 'FRA', 'CRO'),
 (2002, '31 May 2002 - 20:30 ', 'Group A', 'Seoul World Cup Stadium', 'Seoul ', 'France', 0, 1, 'Senegal', ' ', 62561.0, 0, 1, 'BUJSAIM Ali (UAE)', 'ALTRAIFI Ali (KSA)', 'RATTALINO Jorge (ARG)', 43950100, 43950001, 'FRA', 'SEN'),
 (2002, '06 Jun 2002 - 20:30 ', 'Group A', 'Busan Asiad Main Stadium', 'Busan ', 'France', 0, 0, 'Uruguay', ' ', 38289.0, 0, 0, 'RAMOS RIZO Felipe (MEX)', 'FERNANDEZ Vladimir (SLV)', 'CHARLES Curtis (ATG)', 43950100, 43950018, 'FRA', 'URU'),
 (2006, '13 Jun 2006 - 18:00 ', 'Group G', 'Gottlieb-Daimler-Stadion', 'Stuttgart ', 'France', 0, 0, 'Switzerland', ' ', 52000.0, 0, 0, 'IVANOV Valentin (RUS)', 'GOLUBEV Nikolai (RUS)', 'VOLNIN Evgueni (RUS)', 97410100, 97410013, 'FRA', 'SUI'),
 (2006, '18 Jun 2006 - 21:00 ', 'Group G', 'Zentralstadion', 'Leipzig ', 'France', 1, 1, 'Korea Republic', ' ', 43000.0, 1, 0, 'ARCHUNDIA Benito (MEX)', 'RAMIREZ Jose (MEX)', 'VERGARA Hector (CAN)', 97410100, 97410029, 'FRA', 'KOR'),
 (2010, '17 Jun 2010 - 20:30 ', 'Group A', 'Peter Mokaba Stadium', 'Polokwane ', 'France', 0, 2, 'Mexico', ' ', 35370.0, 0, 0, 'AL GHAMDI Khalil (KSA)', 'KAMRANIFAR Hassan (IRN)', 'AL MARZOUQI Saleh (UAE)', 249722, 300061451, 'FRA', 'MEX'),
 (2010, '22 Jun 2010 - 16:00 ', 'Group A', 'Free State Stadium', 'Mangaung/Bloemfontein ', 'France', 1, 2, 'South Africa', ' ', 39415.0, 0, 2, 'RUIZ Oscar (COL)', 'GONZALEZ Abraham (COL)', 'CLAVIJO Humberto (COL)', 249722, 300061449, 'FRA', 'RSA'),
 (2014, '15 Jun 2014 - 16:00 ', 'Group E', 'Estadio Beira-Rio', 'Porto Alegre ', 'France', 3, 0, 'Honduras', ' ', 43012.0, 1, 0, 'RICCI Sandro (BRA)', 'DE CARVALHO Emerson (BRA)', 'VAN GASSE Marcelo (BRA)', 255931, 300186496, 'FRA', 'HON'),
 (2014, '30 Jun 2014 - 13:00 ', 'Round of 16', 'Estadio Nacional', 'Brasilia ', 'France', 2, 0, 'Nigeria', ' ', 67882.0, 0, 0, 'GEIGER Mark (USA)', 'HURD Sean (USA)', 'FLETCHER Joe (CAN)', 255951, 300186462, 'FRA', 'NGA'),
 (2014, '04 Jul 2014 - 13:00 ', 'Quarter-finals', 'Estadio do Maracana', 'Rio De Janeiro ', 'France', 0, 1, 'Germany', ' ', 74240.0, 0, 1, 'PITANA Nestor (ARG)', 'MAIDANA Hernan (ARG)', 'BELATTI Juan Pablo (ARG)', 255953, 300186485, 'FRA', 'GER'),
 (2014, '30 Jun 2014 - 13:00 ', 'Round of 16', 'Estadio Nacional', 'Brasilia ', 'France', 2, 0, 'Nigeria', ' ', 67882.0, 0, 0, 'GEIGER Mark (USA)', 'HURD Sean (USA)', 'FLETCHER Joe (CAN)', 255951, 300186462, 'FRA', 'NGA'),
 (2014, '04 Jul 2014 - 13:00 ', 'Quarter-finals', 'Estadio do Maracana', 'Rio De Janeiro ', 'France', 0, 1, 'Germany', ' ', 74240.0, 0, 1, 'PITANA Nestor (ARG)', 'MAIDANA Hernan (ARG)', 'BELATTI Juan Pablo (ARG)', 255953, 300186485, 'FRA', 'GER')]

## 1.6 Where

In [118]:
# Example 1
# From our Interpol dataset, let's find out which Countries have had three or more than three National Fugitives.
#
%%sql
SELECT * FROM Interpol
WHERE Region = 'Europe';

 * sqlite://
Done.

[('Albania', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif'),
 ('Austria', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/at.gif'),
 ('Belarus', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/by.gif'),
 ('Belgium', 0, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/be.gif'),
 ('Croatia', 1, 1, 1, 'Europe', 'http://www.crwflags.com/fotw/images/h/hr.gif'),
 ('Czech Republic', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/c/cz.gif'),
 ('Denmark', 0, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/d/dk.gif'),
 ('Estonia', 1, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/e/ee.gif'),
 ('Finland', 2, 2, 3, 'Europe', 'http://www.crwflags.com/fotw/images/f/fi.gif'),
 ('France', 0, 0, 7, 'Europe', 'http://www.crwflags.com/fotw/images/f/fr.gif'),
 ('Germany', 1, 0, 3, 'Europe', 'http://www.crwflags.com/fotw/images/d/de.gif'),
 ('Greece', 1, 1, 3, 'Europe', 'http://www.crwflags.com/fotw/images/g/gr.gif'),
 ('Hungary', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/h/hu.gif'),
 ('Ireland', 2, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/i/ie.gif'),
 ('Italy', 1, 1, 3, 'Europe', 'http://www.crwflags.com/fotw/images/i/it.gif'),
 ('Lithuania', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/l/lt.gif'),
 ('Macedonia', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/mk.gif'),
 ('Malta', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/mt.gif'),
 ('Montenegro', 3, 2, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/me.gif'),
 ('Norway', 0, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/n/no.gif'),
 ('Poland', 4, 4, 3, 'Europe', 'http://www.crwflags.com/fotw/images/p/pl.gif'),
 ('Romania', 4, 4, 0, 'Europe', 'http://www.crwflags.com/fotw/images/r/ro.gif'),
 ('Serbia', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/r/rs.gif'),
 ('Slovakia', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/s/sk.gif'),
 ('Spain', 1, 2, 13, 'Europe', 'http://www.crwflags.com/fotw/images/e/es.gif'),
 ('Sweden', 2, 3, 1, 'Europe', 'http://www.crwflags.com/fotw/images/s/se.gif'),
 ('The Netherlands', 6, 3, 8, 'Europe', 'http://www.crwflags.com/fotw/images/n/nl.gif'),
 ('Turkey', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/t/tr.gif'),
 ('Ukraine', 1, 1, 1, 'Europe', 'http://www.crwflags.com/fotw/images/u/ua.gif'),
 ('United Kingdom', 6, 4, 7, 'Europe', 'http://www.crwflags.com/fotw/images/g/gb.gif')]

In [70]:
# Example 2
# From our Interpol dataset, let's get the European countries and the no of Wanted fugitives they have
#
%%sql
SELECT Country, "Wanted Fugitives" FROM Interpol
WHERE Region = 'Europe';

 * sqlite://
Done.

[('Albania', 3),
 ('Austria', 1),
 ('Belarus', 1),
 ('Belgium', 2),
 ('Croatia', 1),
 ('Czech Republic', 3),
 ('Denmark', 2),
 ('Estonia', 2),
 ('Finland', 2),
 ('France', 0),
 ('Germany', 0),
 ('Greece', 1),
 ('Hungary', 2),
 ('Ireland', 1),
 ('Italy', 1),
 ('Lithuania', 1),
 ('Macedonia', 0),
 ('Malta', 0),
 ('Montenegro', 2),
 ('Norway', 1),
 ('Poland', 4),
 ('Romania', 4),
 ('Serbia', 0),
 ('Slovakia', 2),
 ('Spain', 2),
 ('Sweden', 3),
 ('The Netherlands', 3),
 ('Turkey', 0),
 ('Ukraine', 1),
 ('United Kingdom', 4)]

In [71]:
# Example 3
# From our WorldCup dataset, Let us select the home teams, away teams 
# and the respective no. of home team goals, no. of away team goals
# for the years after 1950
#
%%sql
SELECT Year, Stage, Home_Team_Name, Home_Team_Goals, Away_Team_Name, Away_Team_Goals FROM WorldCup
WHERE Year > 1930
LIMIT 7;

 * sqlite://
Done.

[(1934, 'Preliminary round', 'Austria', 3, 'France', 2),
 (1934, 'Preliminary round', 'Hungary', 4, 'Egypt', 2),
 (1934, 'Preliminary round', 'Switzerland', 3, 'Netherlands', 2),
 (1934, 'Preliminary round', 'Sweden', 3, 'Argentina', 2),
 (1934, 'Preliminary round', 'Germany', 5, 'Belgium', 2),
 (1934, 'Preliminary round', 'Spain', 3, 'Brazil', 1),
 (1934, 'Preliminary round', 'Italy', 7, 'USA', 1)]

### <font color="green"> 1.6 Challenges</font>

In [81]:
# Challenge 1
# From our Interpol dataset, find out which  country had the most Captured Fugitives 
#
%%sql
SELECT Country FROM Interpol
ORDER BY "Captured Fugitives" DESC
LIMIT 1;

 * sqlite://
Done.

[('Albania',)]

In [129]:
# Challenge 2
# Using our Interpol dataset, get the european and asian countries;
#
%%sql
SELECT Country FROM Interpol 
WHERE Region = 'Europe' AND 'Asia';

 * sqlite://
Done.

[]

In [78]:
# Challenge 3 
# From our Interpol dataset, find out which top countries had the least National fugities
#
%%sql
SELECT Country, "National Fugitives" FROM Interpol
ORDER BY "National Fugitives" DESC
LIMIT 5;

 * sqlite://
Done.

[('United States', 8),
 ('The Netherlands', 6),
 ('United Kingdom', 6),
 ('Poland', 4),
 ('Romania', 4)]

## 1.7 Between

In [136]:
# Example 1
# Select the countries with national fugitives between 0 and 3 ordered by nationnal fugitives ascending order
#
%%sql
SELECT Country, "National Fugitives" FROM Interpol
WHERE "National Fugitives" BETWEEN 0 AND 3 ORDER BY "National Fugitives" ASC;

 * sqlite://
Done.

[('Angola', 0),
 ('Belgium', 0),
 ('Bolivia', 0),
 ('Botswana', 0),
 ('Cambodia', 0),
 ('Cayman Islands', 0),
 ('Congo', 0),
 ('Costa Rica', 0),
 ('Curaçao', 0),
 ('Denmark', 0),
 ('Ecuador', 0),
 ('France', 0),
 ('India', 0),
 ('Lesotho', 0),
 ('Macedonia', 0),
 ('Mali', 0),
 ('Malta', 0),
 ('Mozambique', 0),
 ('Namibia', 0),
 ('New Zealand', 0),
 ('Norway', 0),
 ('Panama', 0),
 ('Qatar', 0),
 ('Serbia', 0),
 ('Tanzania', 0),
 ('Turkey', 0),
 ('Venezuela', 0),
 ('Zimbabwe', 0),
 ('Australia', 1),
 ('Austria', 1),
 ('Belarus', 1),
 ('Belize', 1),
 ('Chile', 1),
 ('Croatia', 1),
 ('Dominican Republic', 1),
 ('Estonia', 1),
 ('Germany', 1),
 ('Greece', 1),
 ('Honduras', 1),
 ('Indonesia', 1),
 ('Iraq', 1),
 ('Italy', 1),
 ('Kenya', 1),
 ('Lithuania', 1),
 ('Nicaragua', 1),
 ('Pakistan', 1),
 ('Paraguay', 1),
 ('Somalia', 1),
 ('Spain', 1),
 ('Swaziland', 1),
 ('Ukraine', 1),
 ('Uruguay', 1),
 ('Zambia', 1),
 ('Argentina', 2),
 ('Bangladesh', 2),
 ('Brazil', 2),
 ('El Salvador', 2),
 ('Finland', 2),
 ('Georgia, Asia', 2),
 ('Hungary', 2),
 ('Ireland', 2),
 ('Morocco', 2),
 ('Peru', 2),
 ('Russia', 2),
 ('Slovakia', 2),
 ('Sweden', 2),
 ('Albania', 3),
 ('Canada', 3),
 ('Colombia', 3),
 ('Czech Republic', 3),
 ('Mexico', 3),
 ('Montenegro', 3),
 ('South Africa', 3)]

In [139]:
# Example 2
# Select the countries with national fugitives not between 0 and 4 ordered by nationnal fugitives ascending order
#
%%sql
SELECT Country, "National Fugitives" FROM Interpol
WHERE "National Fugitives" NOT BETWEEN 0 AND 4 ORDER BY "National Fugitives" ASC;

 * sqlite://
Done.

[('The Netherlands', 6), ('United Kingdom', 6), ('United States', 8)]

In [147]:
# Example 3
# Select any 5 matches played after 1950 which did not have the home team as Germany
#
%%sql
SELECT * FROM WorldCup
WHERE NOT "Home Team Name" = 'Germany' AND NOT Year > 1950
LIMIT 5;

 * sqlite://
Done.

[(1930, '13 Jul 1930 - 15:00 ', 'Group 1', 'Pocitos', 'Montevideo ', 'France', 4, 1, 'Mexico', ' ', 4444.0, 3, 0, 'LOMBARDI Domingo (URU)', 'CRISTOPHE Henry (BEL)', 'REGO Gilberto (BRA)', 201, 1096, 'FRA', 'MEX'),
 (1930, '13 Jul 1930 - 15:00 ', 'Group 4', 'Parque Central', 'Montevideo ', 'USA', 3, 0, 'Belgium', ' ', 18346.0, 2, 0, 'MACIAS Jose (ARG)', 'MATEUCCI Francisco (URU)', 'WARNKEN Alberto (CHI)', 201, 1090, 'USA', 'BEL'),
 (1930, '14 Jul 1930 - 12:45 ', 'Group 2', 'Parque Central', 'Montevideo ', 'Yugoslavia', 2, 1, 'Brazil', ' ', 24059.0, 2, 0, 'TEJADA Anibal (URU)', 'VALLARINO Ricardo (URU)', 'BALWAY Thomas (FRA)', 201, 1093, 'YUG', 'BRA'),
 (1930, '14 Jul 1930 - 14:50 ', 'Group 3', 'Pocitos', 'Montevideo ', 'Romania', 3, 1, 'Peru', ' ', 2549.0, 1, 0, 'WARNKEN Alberto (CHI)', 'LANGENUS Jean (BEL)', 'MATEUCCI Francisco (URU)', 201, 1098, 'ROU', 'PER'),
 (1930, '15 Jul 1930 - 16:00 ', 'Group 1', 'Parque Central', 'Montevideo ', 'Argentina', 1, 0, 'France', ' ', 23409.0, 0, 0, 'REGO Gilberto (BRA)', 'SAUCEDO Ulises (BOL)', 'RADULESCU Constantin (ROU)', 201, 1085, 'ARG', 'FRA')]

### <font color="green"> 1.7 Challenges</font>

In [144]:
# Challenge 1
# From the Interpol dataset, get all asian countries with wanted fugitives between 0 and 2
#
%%sql
SELECT Country FROM Interpol
WHERE Region = 'Asia' AND "Wanted Fugitives" BETWEEN 0 AND 2;

 * sqlite://
Done.

[('Bangladesh',),
 ('Cambodia',),
 ('Georgia, Asia',),
 ('India',),
 ('Indonesia',),
 ('Iraq',),
 ('Pakistan',),
 ('Qatar',)]

In [146]:
# Challenge 2
# From the World cup dataset, get all the matches that were played later than 1980 with an attendance less than 5000 
# 
%%sql
SELECT * FROM WorldCup
WHERE Year > 1980 AND Attendance < 5000;

 * sqlite://
Done.

[]

In [149]:
# Challenge 3 
# Which matches were played between the year 1990 and 2000?
# 
%%sql
SELECT * FROM WorldCup BETWEEN 1990 AND 2000;

 * sqlite://
(sqlite3.OperationalError) near "BETWEEN": syntax error
[SQL: SELECT * FROM WorldCup BETWEEN 1990 AND 2000;]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

## 1.8 Distinct

In [130]:
# Example 1
# Let's find out which stadiums have hosted world cup matches
%%sql
SELECT DISTINCT Stadium FROM WorldCup;

 * sqlite://
Done.

[('Pocitos',),
 ('Parque Central',),
 ('Estadio Centenario',),
 ('Stadio Benito Mussolini',),
 ('Giorgio Ascarelli',),
 ('San Siro',),
 ('Littorale',),
 ('Giovanni Berta',),
 ('Luigi Ferraris',),
 ('Nazionale PNF',),
 ('Littorio',),
 ('Parc des Princes',),
 ('Velodrome Municipale',),
 ('Stade Olympique',),
 ('Stade Municipal',),
 ('Stade V�lodrome',),
 ('Stade de la Meinau',),
 ('Cavee Verte',),
 ('Stade du Parc Lescure',),
 ('Victor Boucquey',),
 ('Fort Carree',),
 ('Maracan� - Est�dio Jornalista M�rio Filho',),
 ('Durival de Brito',),
 ('Pacaembu',),
 ('Independencia',),
 ('Eucaliptos',),
 ('Ilha do Retiro',),
 ('Wankdorf Stadium',),
 ('Hardturm',),
 ('Charmilles',),
 ('La Pontaise',),
 ('St. Jakob',),
 ('Comunale di Cornaredo',),
 ('Rasunda Stadium',),
 ('Nya Ullevi',),
 ('Malmo Stadion',),
 ('Jarnvallen',),
 ('Idrottsparken',),
 ('Arosvallen',),
 ('Rimnersvallen',),
 ('Orjans Vall',),
 ('Ryavallen',),
 ('Olympia Stadium',),
 ('Tunavallen',),
 ('Eyravallen',),
 ('Carlos Dittborn',),
 ('Estadio Sausalito',),
 ('Estadio El Teniente-Codelco',),
 ('Nacional',),
 ('Wembley Stadium',),
 ('Hillsborough',),
 ('Goodison Park',),
 ('Ayresome Park',),
 ('Old Trafford Stadium',),
 ('Villa Park',),
 ('Roker Park Ground',),
 ('White City',),
 ('Estadio Azteca',),
 ('Cuauhtemoc',),
 ('Nou Camp - Estadio Le�n',),
 ('Jalisco',),
 ('Luis Dosal',),
 ('Waldstadion',),
 ('Olympiastadion',),
 ('Volksparkstadion',),
 ('Westfalenstadion',),
 ('Niedersachsenstadion',),
 ('Rheinstadion',),
 ('Neckarstadion',),
 ('Parkstadion',),
 ('El Monumental - Estadio Monumental Antonio Vespuci',),
 ('Estadio Jos� Mar�a Minella',),
 ('Arroyito - Estadio Dr. Lisandro de la Torre',),
 ('Jose Amalfitani',),
 ('Estadio Ol�mpico Chateau Carreras',),
 ('San Martin',),
 ('Camp Nou',),
 ('Estadio Municipal de Bala�dos',),
 ('Ramon Sanchez Pizjuan',),
 ('Riazor',),
 ('Nuevo Estadio',),
 ('La Rosaleda',),
 ('El Molinon',),
 ('San Mames',),
 ('Luis Casanova',),
 ('Carlos Tartiere',),
 ('Jose Zorrilla',),
 ('La Romareda',),
 ('Jose Rico Perez',),
 ('Benito Villamarin',),
 ('Vicente Calderon',),
 ('Sarria',),
 ('Santiago Bernabeu',),
 ('Estadio Irapuato',),
 ('Estadio Ol�mpico Universitario',),
 ('Estadio Universitario',),
 ('Tres de Marzo',),
 ('Tecnologico',),
 ('Bombonera - Estadio Nemesio Diez',),
 ('Neza',),
 ('Estadio Corregidora',),
 ('Giuseppe Meazza',),
 ('Stadio San Nicola',),
 ('Renato Dall Ara',),
 ('Stadio Olimpico',),
 ('Comunale',),
 ('Stadio delle Alpi',),
 ('Sant Elia',),
 ('Marc Antonio Bentegodi',),
 ('Della Favorita',),
 ('Dacia Arena',),
 ('San Paolo',),
 ('Friuli',),
 ('Cotton Bowl',),
 ('Soldier Field',),
 ('Pontiac Silverdome',),
 ('Giants Stadium',),
 ('Rose Bowl',),
 ('Citrus Bowl',),
 ('RFK Stadium',),
 ('Stanford Stadium',),
 ('Foxboro Stadium',),
 ('Stade de France',),
 ('La Mosson',),
 ('Stade Felix Bollaert',),
 ('La Beaujoire',),
 ('Stade de Gerland',),
 ('Stade Geoffroy Guichard',),
 ('Seoul World Cup Stadium',),
 ('Munsu Football Stadium',),
 ('Niigata Stadium Big Swan',),
 ('Sapporo Dome',),
 ('Kashima Stadium',),
 ('Busan Asiad Main Stadium',),
 ('Saitama Stadium 2002',),
 ('Gwangju World Cup Stadium',),
 ('Kobe Wing Stadium',),
 ('Suwon World Cup Stadium',),
 ('Daegu World Cup Stadium',),
 ('Jeonju World Cup Stadium',),
 ('Jeju World Cup Stadium',),
 ('Incheon Football Stadium',),
 ('International Stadium Yokohama',),
 ('Miyagi Stadium',),
 ('Oita Stadium Big Eye',),
 ('Shizuoka Stadium Ecopa',),
 ('Osaka Nagai Stadium',),
 ('Daejeon World Cup Stadium',),
 ('FIFA World Cup Stadium, Munich',),
 ('FIFA World Cup Stadium, Gelsenkirchen',),
 ('FIFA World Cup Stadium, Frankfurt',),
 ('FIFA World Cup Stadium, Dortmund',),
 ('FIFA World Cup Stadium, Hamburg',),
 ('Zentralstadion',),
 ('Franken-Stadion',),
 ('FIFA World Cup Stadium, Cologne',),
 ('Fritz-Walter-Stadion',),
 ('FIFA World Cup Stadium, Hanover',),
 ('Gottlieb-Daimler-Stadion',),
 ('Soccer City Stadium',),
 ('Cape Town Stadium',),
 ('Port Elizabeth Stadium',),
 ('Ellis Park Stadium',),
 ('Royal Bafokeng Sports Palace',),
 ('Peter Mokaba Stadium',),
 ('Loftus Versfeld Stadium',),
 ('Durban Stadium',),
 ('Free State Stadium',),
 ('Mbombela Stadium',),
 ('Arena de Sao Paulo',),
 ('Estadio das Dunas',),
 ('Arena Fonte Nova',),
 ('Arena Pantanal',),
 ('Estadio Mineirao',),
 ('Estadio Castelao',),
 ('Arena Amazonia',),
 ('Arena Pernambuco',),
 ('Estadio Nacional',),
 ('Estadio Beira-Rio',),
 ('Estadio do Maracana',),
 ('Arena da Baixada',)]

In [138]:
# Example 2
# Let's find out which world cup cities have hosted world cup matches after 2000
#
%%sql
SELECT DISTINCT City, Year FROM WorldCup WHERE Year > 2000;

 * sqlite://
Done.

[('Seoul ', 2002),
 ('Ulsan ', 2002),
 ('Niigata ', 2002),
 ('Sapporo ', 2002),
 ('Ibaraki ', 2002),
 ('Busan ', 2002),
 ('Saitama ', 2002),
 ('Gwangju ', 2002),
 ('Kobe ', 2002),
 ('Suwon ', 2002),
 ('Daegu ', 2002),
 ('Jeonju ', 2002),
 ('Jeju ', 2002),
 ('Incheon ', 2002),
 ('Yokohama ', 2002),
 ('Rifu ', 2002),
 ('Oita ', 2002),
 ('Shizuoka ', 2002),
 ('Osaka ', 2002),
 ('Daejeon ', 2002),
 ('Munich ', 2006),
 ('Gelsenkirchen ', 2006),
 ('Frankfurt/Main ', 2006),
 ('Dortmund ', 2006),
 ('Hamburg ', 2006),
 ('Leipzig ', 2006),
 ('Nuremberg ', 2006),
 ('Cologne ', 2006),
 ('Kaiserslautern ', 2006),
 ('Hanover ', 2006),
 ('Stuttgart ', 2006),
 ('Berlin ', 2006),
 ('Johannesburg ', 2010),
 ('Cape Town ', 2010),
 ('Nelson Mandela Bay/Port Elizabeth ', 2010),
 ('Phokeng ', 2010),
 ('Polokwane ', 2010),
 ('Tshwane/Pretoria ', 2010),
 ('Durban ', 2010),
 ('Mangaung/Bloemfontein ', 2010),
 ('Nelspruit ', 2010),
 ('Sao Paulo ', 2014),
 ('Natal ', 2014),
 ('Salvador ', 2014),
 ('Cuiaba ', 2014),
 ('Belo Horizonte ', 2014),
 ('Fortaleza ', 2014),
 ('Manaus ', 2014),
 ('Recife ', 2014),
 ('Brasilia ', 2014),
 ('Porto Alegre ', 2014),
 ('Rio De Janeiro ', 2014),
 ('Curitiba ', 2014)]

### <font color="green"> 1.8 Challenges</font>

In [133]:
# Challenge 1
# Name the stages in the world cup and order them alphabetically by stage.
# 
%%sql
SELECT DISTINCT Stage FROM WorldCup ORDER BY Stage ASC;

 * sqlite://
Done.

[('Final',),
 ('First round',),
 ('Group 1',),
 ('Group 2',),
 ('Group 3',),
 ('Group 4',),
 ('Group 5',),
 ('Group 6',),
 ('Group A',),
 ('Group B',),
 ('Group C',),
 ('Group D',),
 ('Group E',),
 ('Group F',),
 ('Group G',),
 ('Group H',),
 ('Match for third place',),
 ('Play-off for third place',),
 ('Preliminary round',),
 ('Quarter-finals',),
 ('Round of 16',),
 ('Semi-finals',),
 ('Third place',)]

In [137]:
# Challenge 2
# Which cities hosted the world cup between 1950 and 2000?
#
%%sql
SELECT DISTINCT City FROM WorldCup WHERE Year BETWEEN 1950 AND 2000;

 * sqlite://
Done.

[('Rio De Janeiro ',),
 ('Curitiba ',),
 ('Sao Paulo ',),
 ('Belo Horizonte ',),
 ('Porto Alegre ',),
 ('Recife ',),
 ('Berne ',),
 ('Zurich ',),
 ('Geneva ',),
 ('Lausanne ',),
 ('Basel ',),
 ('Lugano ',),
 ('Solna ',),
 ('Gothenburg ',),
 ('Malm� ',),
 ('Sandviken ',),
 ('Norrk�Ping ',),
 ('Vasteras ',),
 ('Udevalla ',),
 ('Halmstad ',),
 ('Boras ',),
 ('Helsingborg ',),
 ('Eskilstuna ',),
 ('Orebro ',),
 ('Arica ',),
 ('Vina Del Mar ',),
 ('Rancagua ',),
 ('Santiago De Chile ',),
 ('London ',),
 ('Sheffield ',),
 ('Liverpool ',),
 ('Middlesbrough ',),
 ('Manchester ',),
 ('Birmingham ',),
 ('Sunderland ',),
 ('Mexico City ',),
 ('Puebla ',),
 ('Leon ',),
 ('Guadalajara ',),
 ('Toluca ',),
 ('Frankfurt/Main ',),
 ('Berlin West ',),
 ('Hamburg ',),
 ('Dortmund ',),
 ('Hanover ',),
 ('D�Sseldorf ',),
 ('Munich ',),
 ('Stuttgart ',),
 ('Gelsenkirchen ',),
 ('Buenos Aires ',),
 ('Mar Del Plata ',),
 ('Rosario ',),
 ('Cordoba ',),
 ('Mendoza ',),
 ('Barcelona ',),
 ('Vigo ',),
 ('Seville ',),
 ('La Coru�A ',),
 ('Elche ',),
 ('Malaga ',),
 ('Gijon ',),
 ('Bilbao ',),
 ('Valencia ',),
 ('Oviedo ',),
 ('Valladolid ',),
 ('Zaragoza ',),
 ('Alicante ',),
 ('Madrid ',),
 ('Irapuato ',),
 ('Monterrey ',),
 ('Nezahualcoyotl ',),
 ('Queretaro ',),
 ('Milan ',),
 ('Bari ',),
 ('Bologna ',),
 ('Rome ',),
 ('Florence ',),
 ('Turin ',),
 ('Genoa ',),
 ('Cagliari ',),
 ('Verona ',),
 ('Palermo ',),
 ('Udine ',),
 ('Naples ',),
 ('Dallas ',),
 ('Chicago ',),
 ('Detroit ',),
 ('New York/New Jersey ',),
 ('Los Angeles ',),
 ('Orlando ',),
 ('Washington Dc ',),
 ('San Francisco ',),
 ('Boston ',),
 ('Saint-Denis ',),
 ('Montpellier ',),
 ('Bordeaux ',),
 ('Toulouse ',),
 ('Lens ',),
 ('Marseilles ',),
 ('Nantes ',),
 ('Lyon ',),
 ('Saint-Etienne ',),
 ('Paris ',)]

In [135]:
# Challenge 3
# During which years was the world cup hosted in?
#
%%sql
SELECT DISTINCT Year FROM WorldCup;

 * sqlite://
Done.

[(1930,),
 (1934,),
 (1938,),
 (1950,),
 (1954,),
 (1958,),
 (1962,),
 (1966,),
 (1970,),
 (1974,),
 (1978,),
 (1982,),
 (1986,),
 (1990,),
 (1994,),
 (1998,),
 (2002,),
 (2006,),
 (2010,),
 (2014,)]

## 1.9 Count

In [112]:
# Example 1
# How many countries were listed in interpol's data? 
#
%%sql
SELECT COUNT(Country) FROM Interpol;

 * sqlite://
Done.

[(78,)]

In [113]:
# Example 2
# How many times has Brazil played home during world cup matches?
#
%%sql
SELECT COUNT("Home_Team_Name") FROM WorldCup where Home_Team_Name = 'Brazil';

 * sqlite://
Done.

[(82,)]

In [114]:
# Example 3
# Find out the number of times that stadiums have hosted matches in the World Cup? 
# 
%%sql
SELECT COUNT(Stadium)
FROM WorldCup;

 * sqlite://
Done.

[(852,)]

### <font color="green"> 1.9 Challenges</font>

In [125]:
# Challenge 1
# Using Interpol Dataset, find out how many wanted fugitives there are in Northern Africa.
# 
%%sql
SELECT COUNT('Wanted Fugitives')
FROM Interpol
WHERE Region = 'Northern Africa';

 * sqlite://
Done.

[(2,)]

In [128]:
# Challenge 2
# Using Interpol Dataset, find out how many Possible Hosted Fugitives / Captured Fugitives 
# there are in Europe and Northern Africa.
# 
%%sql
SELECT COUNT('Possible Hosted Fugitives/Captured Fugitives')
FROM Interpol
WHERE Region = 'Europe' AND 'Northern Africa';

 * sqlite://
Done.

[(0,)]

In [127]:
# Challenge 3
# Using WorldCup dataset, find out how many away teams were played where a team scored more than 3 goals.
# 
%%sql
SELECT COUNT(Away_Team_Name)
FROM WorldCup
WHERE Away_Team_Goals > 3;

 * sqlite://
Done.

[(24,)]

## 1.10 Groupby

In [105]:
# Example 1
# Which three stadiums have hosted the most world cup games?
#
%%sql
SELECT Stadium, COUNT(Stadium)
FROM WorldCup
GROUP BY Stadium 
ORDER BY COUNT(Stadium) DESC LIMIT 3;

 * sqlite://
Done.

[('Estadio Azteca', 19), ('Jalisco', 14), ('Olympiastadion', 14)]

In [106]:
# Example 2
# Which three stadiums have hosted the least world cup games?
#
%%sql
SELECT City, COUNT(Stadium)
FROM WorldCup
GROUP BY Stadium 
ORDER BY COUNT(Stadium) ASC LIMIT 3;

 * sqlite://
Done.

[('Le Havre ', 1), ('Lugano ', 1), ('Orebro ', 1)]

### <font color="green"> 1.10 Challenges</font>

In [111]:
# Challenge 1
# What has been the largest no. of home goals scored by three home teams? 
# 
%%sql
SELECT Home_Team_Name, COUNT(Home_Team_Goals)
FROM WorldCup
GROUP BY Home_Team_Name
ORDER BY COUNT(Home_Team_Goals) DESC LIMIT 3;

 * sqlite://
Done.

[('Brazil', 82), ('Italy', 57), ('Argentina', 54)]

In [110]:
# Challenge 2
# Which away teams have scored the lowest no. of away goals?
# 
%%sql
SELECT Away_Team_Name, COUNT(Away_Team_Goals)
FROM WorldCup
GROUP BY Away_Team_Name 
ORDER BY COUNT(Away_Team_Goals) ASC LIMIT 5;

 * sqlite://
Done.

[('Cuba', 1),
 ('Czech Republic', 1),
 ('Dutch East Indies', 1),
 ('Iraq', 1),
 ('Togo', 1)]

In [109]:
# Challenge 3
# Select records from the World Cup Dataset grouping by City 
# 
%%sql
SELECT City
FROM WorldCup
GROUP BY City
LIMIT 10;

 * sqlite://
Done.

[('Alicante ',),
 ('Antibes ',),
 ('Arica ',),
 ('Barcelona ',),
 ('Bari ',),
 ('Basel ',),
 ('Belo Horizonte ',),
 ('Berlin ',),
 ('Berlin West ',),
 ('Berne ',)]

##1.11 Null Values

In [100]:
# Example 1
# Select any one record from the world cup dataset that has null examples?
# 
%%sql
SELECT *
FROM WorldCup
WHERE Attendance IS NULL LIMIT 1;

 * sqlite://
Done.

[(2014, '30 Jun 2014 - 17:00 ', 'Round of 16', 'Estadio Beira-Rio', 'Porto Alegre ', 'Germany', 2, 1, 'Algeria', 'Germany win after extra time ', None, 0, 0, 'RICCI Sandro (BRA)', 'DE CARVALHO Emerson (BRA)', 'VAN GASSE Marcelo (BRA)', 255951, 300186460, 'GER', 'ALG')]

In [101]:
# Example 2
# Select any 5 records without null examples from the Worldcup Dataset 
#
%%sql
SELECT *
FROM WorldCup
WHERE City IS NOT NULL
LIMIT 5;

 * sqlite://
Done.

[(1930, '13 Jul 1930 - 15:00 ', 'Group 1', 'Pocitos', 'Montevideo ', 'France', 4, 1, 'Mexico', ' ', 4444.0, 3, 0, 'LOMBARDI Domingo (URU)', 'CRISTOPHE Henry (BEL)', 'REGO Gilberto (BRA)', 201, 1096, 'FRA', 'MEX'),
 (1930, '13 Jul 1930 - 15:00 ', 'Group 4', 'Parque Central', 'Montevideo ', 'USA', 3, 0, 'Belgium', ' ', 18346.0, 2, 0, 'MACIAS Jose (ARG)', 'MATEUCCI Francisco (URU)', 'WARNKEN Alberto (CHI)', 201, 1090, 'USA', 'BEL'),
 (1930, '14 Jul 1930 - 12:45 ', 'Group 2', 'Parque Central', 'Montevideo ', 'Yugoslavia', 2, 1, 'Brazil', ' ', 24059.0, 2, 0, 'TEJADA Anibal (URU)', 'VALLARINO Ricardo (URU)', 'BALWAY Thomas (FRA)', 201, 1093, 'YUG', 'BRA'),
 (1930, '14 Jul 1930 - 14:50 ', 'Group 3', 'Pocitos', 'Montevideo ', 'Romania', 3, 1, 'Peru', ' ', 2549.0, 1, 0, 'WARNKEN Alberto (CHI)', 'LANGENUS Jean (BEL)', 'MATEUCCI Francisco (URU)', 201, 1098, 'ROU', 'PER'),
 (1930, '15 Jul 1930 - 16:00 ', 'Group 1', 'Parque Central', 'Montevideo ', 'Argentina', 1, 0, 'France', ' ', 23409.0, 0, 0, 'REGO Gilberto (BRA)', 'SAUCEDO Ulises (BOL)', 'RADULESCU Constantin (ROU)', 201, 1085, 'ARG', 'FRA')]

### <font color="green"> 1.11 Challenges</font>

In [102]:
# Challenge 1
# Using the Worldcup dataset, select all the records that contain null values?
#
%%sql
SELECT * FROM WorldCup LIMIT 5;

 * sqlite://
Done.

[(1930, '13 Jul 1930 - 15:00 ', 'Group 1', 'Pocitos', 'Montevideo ', 'France', 4, 1, 'Mexico', ' ', 4444.0, 3, 0, 'LOMBARDI Domingo (URU)', 'CRISTOPHE Henry (BEL)', 'REGO Gilberto (BRA)', 201, 1096, 'FRA', 'MEX'),
 (1930, '13 Jul 1930 - 15:00 ', 'Group 4', 'Parque Central', 'Montevideo ', 'USA', 3, 0, 'Belgium', ' ', 18346.0, 2, 0, 'MACIAS Jose (ARG)', 'MATEUCCI Francisco (URU)', 'WARNKEN Alberto (CHI)', 201, 1090, 'USA', 'BEL'),
 (1930, '14 Jul 1930 - 12:45 ', 'Group 2', 'Parque Central', 'Montevideo ', 'Yugoslavia', 2, 1, 'Brazil', ' ', 24059.0, 2, 0, 'TEJADA Anibal (URU)', 'VALLARINO Ricardo (URU)', 'BALWAY Thomas (FRA)', 201, 1093, 'YUG', 'BRA'),
 (1930, '14 Jul 1930 - 14:50 ', 'Group 3', 'Pocitos', 'Montevideo ', 'Romania', 3, 1, 'Peru', ' ', 2549.0, 1, 0, 'WARNKEN Alberto (CHI)', 'LANGENUS Jean (BEL)', 'MATEUCCI Francisco (URU)', 201, 1098, 'ROU', 'PER'),
 (1930, '15 Jul 1930 - 16:00 ', 'Group 1', 'Parque Central', 'Montevideo ', 'Argentina', 1, 0, 'France', ' ', 23409.0, 0, 0, 'REGO Gilberto (BRA)', 'SAUCEDO Ulises (BOL)', 'RADULESCU Constantin (ROU)', 201, 1085, 'ARG', 'FRA')]

In [104]:
# Challenge 2
# Select all the records that do not contain null values from the Interpol dataset
#
%%sql
SELECT * FROM Interpol LIMIT 5;

 * sqlite://
Done.

[('Albania', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif'),
 ('Angola', 0, 0, 1, 'Northern Africa', 'http://www.crwflags.com/fotw/images/a/ao.gif'),
 ('Argentina', 2, 2, 1, 'South America', 'http://www.crwflags.com/fotw/images/a/ar.gif'),
 ('Australia', 1, 1, 2, 'Oceania', 'http://www.crwflags.com/fotw/images/a/au.gif'),
 ('Austria', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/at.gif')]